In [15]:
import pandas as pd
import requests
from io import StringIO

# orig_url = 'https://drive.google.com/file/d/1DEMmvMdEgUjvLa5m-0JNyoFxGJhbmnFL/view?usp=sharing' # stollen1
orig_url = 'https://drive.google.com/file/d/1Gq9beJ456xaTC_v6iwVSEQ-R5Q0UViUH/view?usp=sharing' # stollen

file_id = orig_url.split('/')[-2]
dwn_url = 'https://drive.google.com/uc?export=download&id=' + file_id
url = requests.get(dwn_url).text
csv_raw = StringIO(url)
df = pd.read_csv(csv_raw)
df

   ï»¿"Geregistreerde diefstallen; diefstallen en verdachten   regio"
0                Gebruik van Geweld: Alle diefstallen             NaN
1                                  Regio's: Nederland             NaN
2       Onderwerp: |Totaal geregistreerde diefstallen             NaN
3                                         ;"Perioden"             NaN
4   ;"2010";"2011";"2012";"2013";"2014";"2015";"20...             NaN
5   Soort diefstal;"aantal";"aantal";"aantal";"aan...             NaN
6   Alle diefstallen;"670470";"677970";"656450";"6...             NaN
7   Diefstal van fiets;"107465";"105690";"106260";...             NaN
8   Diefstal van bromfiets/snorfiets;"17345";"1840...             NaN
9   Diefstal van motor/scooter;"2465";"2430";"2155...             NaN
10  Diefstal van personenauto;"14450";"13605";"127...             NaN
11  Diefstal van vervoermiddel (overig);"5165";"53...             NaN
12  Diefstal van vaartuig;"1180";"1175";"1065";"10...             NaN
13  Diefstal uit/vanaf personenauto;"121685";"1152...             NaN
14  Diefstal uit/vanaf vervoermiddel(overig);"1785...             NaN
15  Diefstal uit/vanaf vaartuig;"2040";"2070";"219...             NaN
16  Diefstal van dier;"345";"335";"345";"255";"255...             NaN
17  Straatroof;"8260";"8525";"8155";"7180";"5525";...             NaN
18  Zakkenrollerij;"33425";"35290";"38945";"43945"...             NaN
19  Totaal diefstal uit woning/schuur/e.d.;"102745...             NaN
20  Diefstal/inbraak uit woning;"82690";"89145";"9...             NaN
21  Diefstal/inbraak uit schuur/garage/e.d;"20055"...             NaN
22  Winkeldiefstal;"41345";"42610";"42775";"43555"...             NaN
23  Diefstal/inbraak uit winkel/bedrijf/e.d.;"3496...             NaN
24  Diefstal/inbraak uit hotel/pension;"910";"750"...             NaN
25  Diefstal/inbraak uit school;"5250";"4675";"426...             NaN
26  Diefstal/inbraak uit sportcomplex;"5140";"5505...             NaN
27  Diefstal/inbraak uit defensiecomplex;"670";"68...             NaN
28  Diefstal/inbraak uit gebouw (overig);"10635";"...             NaN
29  Overval;"2770";"2520";"2135";"1705";"1330";"12...             NaN
30  Diefstal en inbraak (overig);"134380";"145170"...             NaN
31                                          Bron: CBS             NaN