In [14]:
import pandas as pd
import requests
from io import StringIO

orig_url='https://drive.google.com/file/d/1DEMmvMdEgUjvLa5m-0JNyoFxGJhbmnFL/view?usp=sharing'

file_id = orig_url.split('/')[-2]
dwn_url='https://drive.google.com/uc?export=download&id=' + file_id
url = requests.get(dwn_url).text
csv_raw = StringIO(url)
df = pd.read_csv(csv_raw)
df

   ï»¿";""2010"";""2011"";""2012"";""2013"";""2014"";""2015"";""2016"";""2017"";""2018*"";""2019*"""
0   Soort diefstal;"aantal";"aantal";"aantal";"aan...
1   Alle diefstallen;"670470";"677970";"656450";"6...
2   Diefstal van fiets;"107465";"105690";"106260";...
3   Diefstal van bromfiets/snorfiets;"17345";"1840...
4   Diefstal van motor/scooter;"2465";"2430";"2155...
5   Diefstal van personenauto;"14450";"13605";"127...
6   Diefstal van vervoermiddel (overig);"5165";"53...
7   Diefstal van vaartuig;"1180";"1175";"1065";"10...
8   Diefstal uit/vanaf personenauto;"121685";"1152...
9   Diefstal uit/vanaf vervoermiddel(overig);"1785...
10  Diefstal uit/vanaf vaartuig;"2040";"2070";"219...
11  Diefstal van dier;"345";"335";"345";"255";"255...
12  Straatroof;"8260";"8525";"8155";"7180";"5525";...
13  Zakkenrollerij;"33425";"35290";"38945";"43945"...
14  Totaal diefstal uit woning/schuur/e.d.;"102745...
15  Diefstal/inbraak uit woning;"82690";"89145";"9...
16  Diefstal/inbraak uit schuur/garage/e.d;"20055"...
17  Winkeldiefstal;"41345";"42610";"42775";"43555"...
18  Diefstal/inbraak uit winkel/bedrijf/e.d.;"3496...
19  Diefstal/inbraak uit hotel/pension;"910";"750"...
20  Diefstal/inbraak uit school;"5250";"4675";"426...
21  Diefstal/inbraak uit sportcomplex;"5140";"5505...
22  Diefstal/inbraak uit defensiecomplex;"670";"68...
23  Diefstal/inbraak uit gebouw (overig);"10635";"...
24  Overval;"2770";"2520";"2135";"1705";"1330";"12...
25  Diefstal en inbraak (overig);"134380";"145170"...
26                                          Bron: CBS